/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.karate.runner;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'gradle.karate.runner.greeting' plugin.
 */
public class GradleKarateRunnerPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.github.prspal.karate-runner");

        // Verify the result
        assertNotNull(project.getTasks().findByName("karate"));
    }
}
